name: Gradle build

on: [push]

jobs:
    test:
        name: Run Hunspell regression tests

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-solrj-${{ hashFiles('versions.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-solrj-
                      ${{ runner.os }}-gradle-
            - name: Initialize gradle settings
              run: ./gradlew localSettings --build-cache -Dscan.tag.exp4 -PgeServer=${{ secrets.GESERVER }} -PgeAccessKey=${{ secrets.GEACCESSKEY }} --info
            - name: Run regular and regression tests
              run: ./gradlew -p lucene/analysis/common clean check testRegressions --build-cache -Dscan.tag.exp5 -Ptests.seed=deadbeef -PgeServer=${{ secrets.GESERVER }} -PgeAccessKey=${{ secrets.GEACCESSKEY }} --info
